import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-community-solar-subscriber-credit-reconciliation",
  "engine": "recovery",
  "title": "Community Solar Subscriber Credit Reconciliation",
  "shortTitle": "Community Solar Subscriber Credit Reconciliation",
  "tagline": "Reconcile utility bill credits and subscriber fees to project production, allocation percentages, and program tariffs.",
  "industry": "Distributed Energy Finance",
  "buyer": "Community solar developers and subscriber managers",
  "uiPort": 4715,
  "apiPort": 5715,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Community Solar Subscriber Credit Reconciliation converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash in one accountable workflow. Reconcile utility bill credits and subscriber fees to project production, allocation percentages, and program tariffs.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Community Solar Subscriber Credit Reconciliation evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("program-tariff-library","CSS01","Program tariff library","Execute program tariff library using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed program tariff library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Program tariff library Reference","text","CSS01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("project-subscriber-registry","CSS02","Project subscriber registry","Execute project subscriber registry using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed project subscriber registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Project subscriber registry Reference","text","CSS02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("subscription-allocation-control","CSS03","Subscription allocation control","Execute subscription allocation control using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed subscription allocation control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Subscription allocation control Reference","text","CSS03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("meter-production-ingestion","CSS04","Meter production ingestion","Execute meter production ingestion using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed meter production ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Meter production ingestion Reference","text","CSS04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("utility-allocation-file","CSS05","Utility allocation file","Execute utility allocation file using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed utility allocation file decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Utility allocation file Reference","text","CSS05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("bill-credit-calculation","CSS06","Bill credit calculation","Execute bill credit calculation using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed bill credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Bill credit calculation Reference","text","CSS06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("low-income-adder","CSS07","Low-income adder","Execute low-income adder using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed low-income adder decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Low-income adder Reference","text","CSS07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("subscription-fee-calculation","CSS08","Subscription fee calculation","Execute subscription fee calculation using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed subscription fee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Subscription fee calculation Reference","text","CSS08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("subscriber-move-handling","CSS09","Subscriber move handling","Execute subscriber move handling using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed subscriber move handling decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Subscriber move handling Reference","text","CSS09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("unallocated-production","CSS10","Unallocated production","Execute unallocated production using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed unallocated production decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Unallocated production Reference","text","CSS10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("utility-statement-matching","CSS11","Utility statement matching","Execute utility statement matching using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed utility statement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Utility statement matching Reference","text","CSS11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("subscriber-invoice-reconciliation","CSS12","Subscriber invoice reconciliation","Execute subscriber invoice reconciliation using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed subscriber invoice reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Subscriber invoice reconciliation Reference","text","CSS12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("utility-dispute-workflow","CSS13","Utility dispute workflow","Execute utility dispute workflow using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed utility dispute workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Utility dispute workflow Reference","text","CSS13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("cash-reconciliation","CSS14","Cash reconciliation","Execute cash reconciliation using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Cash reconciliation Reference","text","CSS14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]}),
feature("project-subscriber-analytics","CSS15","Project subscriber analytics","Execute project subscriber analytics using program tariffs, projects, subscribers, allocations, meter production, utility bill credits, subscription fees, low-income incentives, statements, and cash.","Produce a governed project subscriber analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Project / Subscriber Account","text","Project / Subscriber Account · Standard Case"],["caseReference","Project subscriber analytics Reference","text","CSS15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1497500],["entitledAmount","Contract or Rule-Supported Entitlement","currency",1811975],["domainDriver","Subscriber Class","select","Residential",["Residential","Commercial","Low income"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Program tariff library case","Project subscriber registry case","Subscription allocation control case","Meter production ingestion case","Utility allocation file case"]})
]);
